import { ObjectId } from "mongoose";

class Container {
	_id: string = "";
	ip?: string;
	DeviceName?: string;
	RegionID?: string;
	SystemID?: string;
	CustomerID?: string;
	deviceip?: string;
	Id?: string;
	state?: string;
	comment?: string;
	qamConfig?: object;
	interval?: string;
	ps?: string;
	contimeo?: string;
	tlpktdrop?: string;
	pbkeylen?: string;
	passphrase?: string;
	sourceLatency?: string;
	sourceProtocol?: string;
	sourceEncryption?: string;
	sourceTimeout?: string;
	sourceIP?: string;
	sourcePort?: string;
	sourceSSMIP?: string;
	sourceOutgoingPort?: string;
	sourceAdapter?: string;
	sourceTtl?: string;
	sourceSrtMode?: string;
	sourceDropPackets?: string;
	destProtocol?: string;
	destIP?: string;
	destTtl?: string;
	destPort?: string;
	destOutgoingPort?: string;
	destSrtMode?: string;
	destAdapter?: string;
	destLatency?: string;
	destTimeout?: string;
	destEncryption?: string;
	destDropPackets?: string;
	destDashSegmentDuration?: string;
	destDashMinUpdatePeriod?: string;
	destDashMinBufferTime?: string;
	destDashSuggestedPresentationDelay?: string;
	destDashTimeShiftBufferDepth?: string;
	destDashPreservedSegmentsOutsideOfLiveWindow?: string;
	destDashSegmentTemplateConstantDuration?: string;
	destDashDir?: string;
	destHlsSegmentDuration?: string;
	destHlsFragmentDuration?: string;
	destHlsTimeShiftBufferDepth?: string;
	destHlsPreservedSegmentsOutsideOfLiveWindow?: string;
	destHlsEnableIframe?: string;
	destRtmpLocation?: string;
	inputStream?: string;
	outputStream?: string;
	streamId?: string;
	dir?: string;
	input?: string;
	output?: string;
	streamcomment?: string;
	peerIP?: string;
	status?: string;
	inputStats?: object;
	outputStats?: object;
	Password?: string;
	AuthToken?: string;
	ActionType?: string;
	ActionTime?: Date;
	Module?: string;
	Target?: string;
	Username?: string;
}

export default Container